name: tyba_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sizer: ^2.0.13

  #Logic
  equatable: ^2.0.3
  bloc: ^7.1.0
  flutter_bloc: ^7.3.3
  http: ^0.13.3
  get_it: ^7.2.0
  url_launcher: ^6.0.18

  #Console
  logger: ^1.1.0

  #Render
  flutter_svg: ^1.1.5
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
